window.rozd_combos = [
  {
    video: "anC35O1EHeQ",
    text: [
      {words: "the simplest words explain it all", time: 0},
      {words: "you’re just another voice in her life", time: 29},
      {words: "maybe the harshest, maybe the clearest", time: 37},
      {words: "no one knows what keeps you together", time: 66},
      {words: "what keeps you, besides the fear", time: 88},
      {words: "what keeps you, besides the fear of losing one another", time: 91},
      {words: "the fear of losing one another", time: 93},
      {words: "what can keep together such a torn cloth of epiphany, transformations, and delirium", time: 96},
      {words: "torn cloth of epiphany, transformations, and delirium", time: 105},
      {words: "kept afloat by this weightless apparatus", time: 124},
      {words: "every one of your losses", time: 132},
      {words: "whose flight is weightless, whose drift is delirious", time: 136},
      {words: "things died for are related to life itself", time: 159},
      {words: "things died for are related to life itself, are related to weightlessness, are related to support", time: 168},
      {words: "all those things to which there is no relation", time: 194},
      {words: "all your hesitations, all your doubts, all means of rescue", time: 212},
      {words: "life deserves rapture", time: 260},
      {words: "the Lord forgot about faith long ago", time: 268},
      {words: "neither time nor luck", time: 274},
      {words: "don’t fear death and emptiness", time: 281},
      {words: "God sees the same things you do", time: 289},
      {words: "God sees the same things you do, except that he remembers what he sees", time: 294},
      {words: "you can try to prove something", time: 301},
      {words: "it’s all your fault", time: 311},
      {words: "for some reason, for some end", time: 317},
      {words: "God hides in the grand", time: 334},
      {words: "God is darkness", time: 340},
      {words: "I saw him, I told him that he doesn’t exist", time: 343},
      {words: "this does nothing for me", time: 350},
      {words: "sing, Maria, sing", time: 402},
      {words: "don’t ask awkward questions", time: 405},
      {words: "death does not adjust habits and tastes", time: 409},
      {words: "death adjusts tickets and roadmaps", time: 421},
      {words: "I’m not so spent at this final judgment", time: 427},
      {words: "after living on bread and water in a broken country who can judge me", time: 435},
      {words: "who can judge me and with what can they scare me", time: 442},
      {words: "sing, harpooners, headed for the bottom in the middle of the sea", time: 460},
      {words: "headed for the bottom in the middle of the sea", time: 465},
      {words: "sing, the exiled, let it be known that you don’t care", time: 482},
      {words: "let it be known that you don’t care", time: 488},
      {words: "faith is what keeps you in the saddle", time: 506},
      {words: "faith is what keeps you in the saddle when your chances are so slim, that even your commanders leave you alone", time: 512},
      {words: "the heather and the black grass will flower", time: 523},
      {words: "your rights, a thank you at the end, and a dedication on the first page will always be with you", time: 528},
      {words: "her voices will always be with you", time: 549},
      {words: "birds in a cage", time: 565},
      {words: "the simplest words explain it all", time: 574},
    ]
  }
];
