window.rozd_combos = [
  {
    video: "anC35O1EHeQ",
    text: [
      {words: "the simplest words explain it all", time: 0},
      {words: "you’re just another voice in her life", time: 27},
      {words: "maybe the harshest, maybe the clearest", time: 34},
      {words: "no one knows what keeps you together", time: 64},
      {words: "what keeps you, besides the fear", time: 86},
      {words: "what keeps you, besides the fear of losing one another", time: 89},
      {words: "the fear of losing one another", time: 91},
      {words: "what can keep together such a torn cloth of epiphany, transformations, and delirium", time: 94},
      {words: "torn cloth of epiphany, transformations, and delirium", time: 103},
      {words: "kept afloat by this weightless apparatus", time: 122},
      {words: "every one of your losses", time: 130},
      {words: "whose flight is weightless, whose drift is delirious", time: 134},
      {words: "things died for are related to life itself", time: 157},
      {words: "things died for are related to life itself, are related to weightlessness, are related to support", time: 166},
      {words: "all those things to which there is no relation", time: 192},
      {words: "all your hesitations, all your doubts, all means of rescue", time: 210},
      {words: "life deserves rapture", time: 258},
      {words: "the Lord forgot about faith long ago", time: 266},
      {words: "neither time nor luck", time: 272},
      {words: "don’t fear death and emptiness", time: 279},
      {words: "God sees the same things you do", time: 287},
      {words: "God sees the same things you do, except that he remembers what he sees", time: 292},
      {words: "you can try to prove something", time: 299},
      {words: "it’s all your fault", time: 309},
      {words: "for some reason, for some end", time: 315},
      {words: "God hides in the grand", time: 332},
      {words: "God is darkness", time: 338},
      {words: "I saw him, I told him that he doesn’t exist", time: 341},
      {words: "this does nothing for me", time: 348},
      {words: "sing, Maria, sing", time: 400},
      {words: "don’t ask awkward questions", time: 403},
      {words: "death does not adjust habits and tastes", time: 407},
      {words: "death adjusts tickets and roadmaps", time: 419},
      {words: "I’m not so spent at this final judgment", time: 425},
      {words: "after living on bread and water in a broken country who can judge me", time: 433},
      {words: "who can judge me and with what can they scare me", time: 440},
      {words: "sing, harpooners, headed for the bottom in the middle of the sea", time: 458},
      {words: "headed for the bottom in the middle of the sea", time: 463},
      {words: "sing, the exiled, let it be known that you don’t care", time: 480},
      {words: "let it be known that you don’t care", time: 486},
      {words: "faith is what keeps you in the saddle", time: 504},
      {words: "faith is what keeps you in the saddle when your chances are so slim, that even your commanders leave you alone", time: 510},
      {words: "the heather and the black grass will flower", time: 521},
      {words: "your rights, a thank you at the end, and a dedication on the first page will always be with you", time: 526},
      {words: "her voices will always be with you", time: 547},
      {words: "birds in a cage", time: 563},
      {words: "the simplest words explain it all", time: 572},
    ]
  }
];
